### ISSUE TITLE
should qat model has quantized tensors? 

### ISSUE THREAD

**Issue by fwz-fpga** [daisatojp/PyTorch_QAT_to_EdgeTPU_MNIST#1]
why after running python qat.py  generate fp32 model

**Comment by daisatojp** [comment]
Hi. Quantization Aware Training trains model in 32fp. So resultant weights are fp32. With QAT, the trained weights is more suited to be quantized. You can eventually quantize when you convert tensorflow model (.pb) to tensor lite model (.tflite) with convert_tf_to_tflite.py. Thank you.

**Comment by fwz-fpga** [comment]
Thanks，does torch.onnx.export support export a quantized model with int8 weights?

**Comment by fwz-fpga** [comment]
![image](https://user-images.githubusercontent.com/29475777/113959215-08ab0580-9855-11eb-87b0-f586ab7fec24.png)
this is a tflite qat model.

**Comment by daisatojp** [comment]
Sorry, I have no answer to most of your question.

You can't replace net with net_qat at https://github.com/daisatojp/PyTorch_QAT_to_EdgeTPU_MNIST/blob/master/qat.py#L297
net_qat has PyTorch specific module for QAT which can not be exported to ONNX.

> does torch.onnx.export support export a quantized model with int8 weights?
I don't know.

> this is a tflite qat model. Can pytorch exports qat model same with tflite?
From my understanding, tflite is just for inference, therefore I think it doesn't need QAT specific parameters like FakeQuantWithMinMaxVars. I don't know why such parameters is in tflite model.

> I am confused whether pytorch qat and tf qat with the same mechanism?
I don't think they are exact same mechanism, but I think they essentially follow https://arxiv.org/pdf/1712.05877.pdf

Actually I'm not sure that the procedure of this repository to make quantized model is valid. So please let me know if you notice something wrong. Thank you.

**Comment by fwz-fpga** [comment]
> From my understanding, tflite is just for inference, therefore I think it doesn't need QAT specific parameters like FakeQuantWithMinMaxVars. I don't know why such parameters is in tflite model.

tflite is for inference, that's true. And FakeQuantWithMinMaxVars is the weights of conv  in tflite model ,just in uint8 data type. In tflite model inerence phase, all operations will compute with the uint8 data, rather than fp32.
There is a question I am confused, if pytorch and tf both follow https://arxiv.org/pdf/1712.05877.pdf. Then in the inference phase , pytorch inference with uint8 datatype(same with tflite)  or with int8 datatype. I couldn't find some useful information with pytorch documention. https://pytorch.org/docs/master/quantization.html#quantization-aware-training

**Comment by daisatojp** [comment]
> tflite is for inference, that's true. And FakeQuantWithMinMaxVars is the weights of conv in tflite model ,just in uint8 data type. 

Oh, OK. Then it's fine.

> I couldn't find some useful information with pytorch documention. https://pytorch.org/docs/master/quantization.html#quantization-aware-training

Year, it's not clear what theory based on in PyTorchQAT.

> In tflite model inference phase, all operations will compute with the uint8 data, rather than fp32.
There is a question I am confused, if pytorch and tf both follow https://arxiv.org/pdf/1712.05877.pdf. Then in the inference phase , pytorch inference with uint8 datatype(same with tflite) or with int8 datatype.

In tflite, currently, it looks like multiply is int8, and addition is int32 internally. (ref https://www.tensorflow.org/lite/performance/quantization_spec#int8_quantized_operator_specifications). I guess it is almost same in PyTorch.

By the way, I rethink the procedure of this repository. Currently, the procedure is, PyTorchQAT (fp32) -> onnx (fp32) -> tensorflow (fp32) -> tflite (uint8). But when it converts tensorflow to tflite, it does post-training quantization because zero_points and scales are unknown at this time. (ref https://www.tensorflow.org/lite/performance/quantization_spec). As a result, it is nothing but post-training quantization, not QAT.

To get PyTorchQAT properly, I think there are 2 options,
* truly quantize at PyTorch model. I mean PyTorch(QAT) (fp32) -> PyTorch(int8) -> onnx (int8) -> tensorflow (int8) -> tflite (int8). 
* transfer zero_points and scales from the result of PyTorchQAT to tflite

Either way looks hard, but I try to investigate. Because I want to QAT and I hate tensorflow :)

**Comment by fwz-fpga** [comment]
Thanks, 
From https://www.tensorflow.org/lite/guide/hosted_models , I download some qat models and find them with uint8 weights and run with uint8 operators(source build tflite).  
So the link you mentioned above(https://www.tensorflow.org/lite/performance/quantization_spec#int8_quantized_operator_specifications)  maybe post-training quantized model use int8? 
Another guess: tflite older version use uint8 , future will use int8(from above link).

**Comment by daisatojp** [comment]
Yeah, filter type is uint8. It would be worth to notice that bias type is int32. :)

![2021-04-08_230349](https://user-images.githubusercontent.com/4670947/114041205-4ba1c300-98bf-11eb-9154-2f1d345ffc79.jpg)

> Another guess: tflite older version use uint8 , future will use int8(from above link).

I think so. Thank you.

**Comment by daisatojp** [comment]
If you are not satisfied, feel free to reopen. :)
